export const trainersFilters = [
  {
    label: "Skills",
    componentType: "multi-select",
    placeholder: "Select Skills",
    name: "skills",
    options: [
      { id: "corporate-training", label: "Corporate Training" },
      { id: "technical-skills", label: "Technical Skills" },
      { id: "soft-skills", label: "Soft Skills" },
      { id: "leadership-development", label: "Leadership Development" },
      { id: "communication", label: "Communication" },
      { id: "project-management", label: "Project Management" },
      { id: "data-analytics", label: "Data Analytics" },
      { id: "digital-marketing", label: "Digital Marketing" },
      { id: "sales-training", label: "Sales Training" },
      { id: "customer-service", label: "Customer Service" },
    ],
  },
  {
    label: "Industry",
    componentType: "multi-select",
    placeholder: "Select Industry",
    name: "industry",
    options: [
      { id: "technology", label: "Technology" },
      { id: "finance", label: "Finance" },
      { id: "healthcare", label: "Healthcare" },
      { id: "education", label: "Education" },
      { id: "manufacturing", label: "Manufacturing" },
      { id: "sales-marketing", label: "Sales & Marketing" },
      { id: "hr-management", label: "HR & Management" },
      { id: "project-management", label: "Project Management" },
      { id: "soft-skills", label: "Soft Skills" },
      { id: "leadership", label: "Leadership" },
    ],
  },
  {
    label: "Experience",
    componentType: "multi-select",
    placeholder: "Select Experience",
    name: "experience",
    options: [
      { id: "beginner", label: "Beginner (0-2 years)" },
      { id: "intermediate", label: "Intermediate (2-5 years)" },
      { id: "experienced", label: "Experienced (5-10 years)" },
      { id: "expert", label: "Expert (10+ years)" },
    ],
  },
  {
    label: "Location",
    componentType: "multi-select",
    placeholder: "Select Locations",
    name: "location",
    options: [
      { id: "mumbai", label: "Mumbai" },
      { id: "delhi", label: "Delhi" },
      { id: "bangalore", label: "Bangalore" },
      { id: "chennai", label: "Chennai" },
      { id: "hyderabad", label: "Hyderabad" },
      { id: "pune", label: "Pune" },
      { id: "kolkata", label: "Kolkata" },
      { id: "ahmedabad", label: "Ahmedabad" },
      { id: "jaipur", label: "Jaipur" },
      { id: "surat", label: "Surat" },
    ],
  },
];

// Mock data removed - now using API data
