export const companiesFilters = [
  {
    label: "Status",
    componentType: "multi-select",
    placeholder: "Select Status",
    name: "status",
    options: [
      { id: "active", label: "Active" },
      { id: "inactive", label: "Inactive" },
    ],
  },
  {
    label: "Verification",
    componentType: "multi-select",
    placeholder: "Select Verification",
    name: "verification",
    options: [
      { id: "verified", label: "Verified" },
      { id: "unverified", label: "Unverified" },
    ],
  },
  {
    label: "Industry",
    componentType: "multi-select",
    placeholder: "Select Industries",
    name: "industry",
    options: [
      { id: "technology", label: "Technology" },
      { id: "healthcare", label: "Healthcare" },
      { id: "education", label: "Education" },
      { id: "finance", label: "Finance" },
      { id: "retail", label: "Retail" },
      { id: "manufacturing", label: "Manufacturing" },
      { id: "consulting", label: "Consulting" },
      { id: "telecommunications", label: "Telecommunications" },
      { id: "automotive", label: "Automotive" },
      { id: "real-estate", label: "Real Estate" },
      { id: "media", label: "Media & Entertainment" },
      { id: "logistics", label: "Logistics & Transportation" },
    ],
  },
  {
    label: "Company Size",
    componentType: "multi-select",
    placeholder: "Select Company Size",
    name: "companySize",
    options: [
      { id: "startup", label: "Startup (1-10)" },
      { id: "small", label: "Small (11-50)" },
      { id: "medium", label: "Medium (51-200)" },
      { id: "large", label: "Large (201-1000)" },
      { id: "enterprise", label: "Enterprise (1000+)" },
    ],
  },
  {
    label: "Location",
    componentType: "multi-select",
    placeholder: "Select Locations",
    name: "location",
    options: [
      { id: "mumbai", label: "Mumbai" },
      { id: "delhi", label: "Delhi" },
      { id: "bangalore", label: "Bangalore" },
      { id: "chennai", label: "Chennai" },
      { id: "hyderabad", label: "Hyderabad" },
      { id: "pune", label: "Pune" },
      { id: "kolkata", label: "Kolkata" },
      { id: "ahmedabad", label: "Ahmedabad" },
      { id: "jaipur", label: "Jaipur" },
      { id: "surat", label: "Surat" },
    ],
  },
  {
    label: "Sort By",
    componentType: "select",
    placeholder: "Select Sort Field",
    name: "sortBy",
    options: [
      { id: "createdAt", label: "Created Date" },
      { id: "updatedAt", label: "Updated Date" },
      { id: "name", label: "Company Name" },
      { id: "industry", label: "Industry" },
      { id: "location", label: "Location" },
    ],
  },
  {
    label: "Sort Order",
    componentType: "select",
    placeholder: "Select Sort Order",
    name: "sortOrder",
    options: [
      { id: "asc", label: "Ascending" },
      { id: "desc", label: "Descending" },
    ],
  },
];
