export const candidatesFilters = [
  {
    label: "Status",
    componentType: "multi-select",
    placeholder: "Select Status",
    name: "status",
    options: [
      { id: "active", label: "Active" },
      { id: "inactive", label: "Inactive" },
      { id: "hired", label: "Hired" },
      { id: "blacklisted", label: "Blacklisted" },
    ],
  },
  {
    label: "Registration Date",
    componentType: "calendar",
    placeholder: "Select Date",
    name: "registrationDate",
  },
  {
    label: "Industry",
    componentType: "multi-select",
    placeholder: "Select Industries",
    name: "industry",
    options: [
      { id: "technology", label: "Technology" },
      { id: "finance", label: "Finance" },
      { id: "healthcare", label: "Healthcare" },
      { id: "education", label: "Education" },
      { id: "manufacturing", label: "Manufacturing" },
      { id: "retail", label: "Retail" },
      { id: "e-commerce", label: "E-commerce" },
      { id: "consulting", label: "Consulting" },
      { id: "media", label: "Media & Entertainment" },
      { id: "real-estate", label: "Real Estate" },
    ],
  },
  {
    label: "Location",
    componentType: "multi-select",
    placeholder: "Select Locations",
    name: "location",
    options: [
      { id: "mumbai", label: "Mumbai" },
      { id: "delhi", label: "Delhi" },
      { id: "bangalore", label: "Bangalore" },
      { id: "chennai", label: "Chennai" },
      { id: "hyderabad", label: "Hyderabad" },
      { id: "pune", label: "Pune" },
      { id: "kolkata", label: "Kolkata" },
      { id: "ahmedabad", label: "Ahmedabad" },
      { id: "jaipur", label: "Jaipur" },
      { id: "surat", label: "Surat" },
    ],
  },
  {
    label: "Experience Level",
    componentType: "multi-select",
    placeholder: "Select Experience",
    name: "experience",
    options: [
      { id: "fresher", label: "Fresher (0-1 years)" },
      { id: "junior", label: "Junior (1-3 years)" },
      { id: "mid-level", label: "Mid-level (3-5 years)" },
      { id: "senior", label: "Senior (5-8 years)" },
      { id: "lead", label: "Lead (8+ years)" },
    ],
  },
  {
    label: "Skills",
    componentType: "multi-select",
    placeholder: "Select Skills",
    name: "skills",
    options: [
      { id: "javascript", label: "JavaScript" },
      { id: "python", label: "Python" },
      { id: "java", label: "Java" },
      { id: "react", label: "React" },
      { id: "nodejs", label: "Node.js" },
      { id: "sql", label: "SQL" },
      { id: "aws", label: "AWS" },
      { id: "docker", label: "Docker" },
      { id: "mongodb", label: "MongoDB" },
      { id: "kubernetes", label: "Kubernetes" },
    ],
  },
];
