export const getCompaniesApprovalFilters = (companyOptions = []) => [
  {
    label: "Status",
    componentType: "select",
    placeholder: "Select Status",
    name: "status",
    options: [
      { id: "approved", label: "Approved" },
      { id: "pending", label: "Pending" },
      { id: "rejected", label: "Rejected" },
    ],
  },
  {
    label: "Date From",
    componentType: "calendar",
    placeholder: "Select From Date",
    name: "dateFrom",
  },
  {
    label: "Date To",
    componentType: "calendar",
    placeholder: "Select To Date",
    name: "dateTo",
  },
  {
    label: "Location",
    componentType: "multi-select",
    placeholder: "Select Locations",
    name: "location",
    options: [
      { id: "mumbai", label: "Mumbai" },
      { id: "delhi", label: "Delhi" },
      { id: "bangalore", label: "Bangalore" },
      { id: "chennai", label: "Chennai" },
      { id: "hyderabad", label: "Hyderabad" },
      { id: "pune", label: "Pune" },
      { id: "kolkata", label: "Kolkata" },
      { id: "ahmedabad", label: "Ahmedabad" },
      { id: "jaipur", label: "Jaipur" },
      { id: "surat", label: "Surat" },
    ],
  },
  {
    label: "Company",
    componentType: "multi-select",
    placeholder: "Select Companies",
    name: "company",
    options: companyOptions,
  },
  {
    label: "Industry",
    componentType: "multi-select",
    placeholder: "Select Industries",
    name: "industry",
    options: [
      { id: "technology", label: "Technology" },
      { id: "healthcare", label: "Healthcare" },
      { id: "education", label: "Education" },
      { id: "finance", label: "Finance" },
      { id: "retail", label: "Retail" },
      { id: "manufacturing", label: "Manufacturing" },
      { id: "consulting", label: "Consulting" },
      { id: "telecommunications", label: "Telecommunications" },
      { id: "automotive", label: "Automotive" },
      { id: "real-estate", label: "Real Estate" },
      { id: "media", label: "Media & Entertainment" },
      { id: "logistics", label: "Logistics & Transportation" },
    ],
  },
];
