export const recruitersFilters = [
  {
    label: "Job Status",
    componentType: "multi-select",
    placeholder: "Select Status",
    name: "jobStatus",
    options: [
      { id: "active", label: "Active" },
      { id: "posted", label: "Posted" },
      { id: "closed", label: "Closed" },
      { id: "draft", label: "Draft" },
      { id: "on-hold", label: "On Hold" },
    ],
  },
  {
    label: "Posted Date",
    componentType: "calendar",
    placeholder: "Select Date",
    name: "postedDate",
  },
  {
    label: "Location",
    componentType: "multi-select",
    placeholder: "Select Locations",
    name: "location",
    options: [
      { id: "mumbai", label: "Mumbai" },
      { id: "delhi", label: "Delhi" },
      { id: "bangalore", label: "Bangalore" },
      { id: "chennai", label: "Chennai" },
      { id: "hyderabad", label: "Hyderabad" },
      { id: "pune", label: "Pune" },
      { id: "kolkata", label: "Kolkata" },
      { id: "ahmedabad", label: "Ahmedabad" },
      { id: "jaipur", label: "Jaipur" },
      { id: "surat", label: "Surat" },
      { id: "noida", label: "Noida" },
      { id: "gurgaon", label: "Gurgaon" },
    ],
  },
  {
    label: "Company",
    componentType: "multi-select",
    placeholder: "Select Companies",
    name: "company",
    options: [
      { id: "tech-corp", label: "Tech Corp" },
      { id: "innovate-solutions", label: "Innovate Solutions" },
      { id: "global-systems", label: "Global Systems" },
      { id: "digital-dynamics", label: "Digital Dynamics" },
      { id: "future-tech", label: "Future Tech" },
      { id: "smart-ventures", label: "Smart Ventures" },
      { id: "nexgen-solutions", label: "NextGen Solutions" },
      { id: "apex-innovations", label: "Apex Innovations" },
      { id: "quantum-systems", label: "Quantum Systems" },
      { id: "synergy-corp", label: "Synergy Corp" },
    ],
  },
  {
    label: "Industry",
    componentType: "multi-select",
    placeholder: "Select Industries",
    name: "industry",
    options: [
      { id: "technology", label: "Technology" },
      { id: "finance", label: "Finance" },
      { id: "healthcare", label: "Healthcare" },
      { id: "education", label: "Education" },
      { id: "manufacturing", label: "Manufacturing" },
      { id: "retail", label: "Retail" },
      { id: "e-commerce", label: "E-commerce" },
      { id: "consulting", label: "Consulting" },
      { id: "media", label: "Media & Entertainment" },
      { id: "real-estate", label: "Real Estate" },
      { id: "telecommunications", label: "Telecommunications" },
      { id: "automotive", label: "Automotive" },
    ],
  },
];

// Mock data for recruiters
export const recruiters = [
  {
    id: "3001",
    name: "Alex Thompson",
    email: "alex.thompson@techcorp.com",
    phone: {
      countryCode: "+91",
      number: "9876543210",
    },
    profileImage: "/person.png",
    designation: "Senior Technical Recruiter",
    company: "Tech Corp",
    lastOrganization: {
      name: "Tech Corp",
      position: "Senior Technical Recruiter",
    },
    industry: "Technology",
    location: "Mumbai",
    jobStatus: "active",
    postedDate: "2024-12-01",
    candidatesCount: 45,
    totalExperience: "6 years",
    sectorSpecialization: [
      { name: "Software Development" },
      { name: "Data Science" },
    ],
    experienceLevel: ["Junior", "Mid-level", "Senior"],
    linkedinProfile: "https://linkedin.com/in/alexthompson",
    fatherName: "Robert Thompson",
    motherName: "Mary Thompson",
    medicalProblemDetails: "",
    currentAddress: {
      address: "123 Tech Street",
      city: "Mumbai",
      state: "Maharashtra",
    },
  },
  {
    id: "3002",
    name: "Sarah Johnson",
    email: "sarah.johnson@innovatesolutions.com",
    phone: {
      countryCode: "+91",
      number: "9876543211",
    },
    profileImage: "/person.png",
    designation: "Talent Acquisition Specialist",
    company: "Innovate Solutions",
    lastOrganization: {
      name: "Innovate Solutions",
      position: "Talent Acquisition Specialist",
    },
    industry: "Finance",
    location: "Delhi",
    jobStatus: "posted",
    postedDate: "2024-11-28",
    candidatesCount: 32,
    totalExperience: "4 years",
    sectorSpecialization: [{ name: "Financial Services" }, { name: "Banking" }],
    experienceLevel: ["Junior", "Mid-level"],
    linkedinProfile: "https://linkedin.com/in/sarahjohnson",
    fatherName: "Michael Johnson",
    motherName: "Jennifer Johnson",
    medicalProblemDetails: "",
    currentAddress: {
      address: "456 Finance Avenue",
      city: "Delhi",
      state: "Delhi",
    },
  },
  {
    id: "3003",
    name: "Michael Chen",
    email: "michael.chen@globalsystems.com",
    phone: {
      countryCode: "+91",
      number: "9876543212",
    },
    profileImage: "/person.png",
    designation: "HR Business Partner",
    company: "Global Systems",
    lastOrganization: {
      name: "Global Systems",
      position: "HR Business Partner",
    },
    industry: "Healthcare",
    location: "Bangalore",
    jobStatus: "active",
    postedDate: "2024-12-03",
    candidatesCount: 28,
    totalExperience: "8 years",
    sectorSpecialization: [
      { name: "Healthcare Technology" },
      { name: "Medical Devices" },
    ],
    experienceLevel: ["Mid-level", "Senior", "Lead"],
    linkedinProfile: "https://linkedin.com/in/michaelchen",
    fatherName: "David Chen",
    motherName: "Lisa Chen",
    medicalProblemDetails: "",
    currentAddress: {
      address: "789 Health Park",
      city: "Bangalore",
      state: "Karnataka",
    },
  },
  {
    id: "3004",
    name: "Emily Rodriguez",
    email: "emily.rodriguez@digitaldynamics.com",
    phone: {
      countryCode: "+91",
      number: "9876543213",
    },
    profileImage: "/person.png",
    designation: "Recruitment Manager",
    company: "Digital Dynamics",
    lastOrganization: {
      name: "Digital Dynamics",
      position: "Recruitment Manager",
    },
    industry: "E-commerce",
    location: "Chennai",
    jobStatus: "closed",
    postedDate: "2024-11-15",
    candidatesCount: 67,
    totalExperience: "5 years",
    sectorSpecialization: [
      { name: "E-commerce" },
      { name: "Digital Marketing" },
    ],
    experienceLevel: ["Junior", "Mid-level"],
    linkedinProfile: "https://linkedin.com/in/emilyrodriguez",
    fatherName: "Carlos Rodriguez",
    motherName: "Maria Rodriguez",
    medicalProblemDetails: "",
    currentAddress: {
      address: "321 Digital Plaza",
      city: "Chennai",
      state: "Tamil Nadu",
    },
  },
  {
    id: "3005",
    name: "David Wilson",
    email: "david.wilson@futuretech.com",
    phone: {
      countryCode: "+91",
      number: "9876543214",
    },
    profileImage: "/person.png",
    designation: "Lead Recruiter",
    company: "Future Tech",
    lastOrganization: {
      name: "Future Tech",
      position: "Lead Recruiter",
    },
    industry: "Technology",
    location: "Hyderabad",
    jobStatus: "active",
    postedDate: "2024-12-05",
    candidatesCount: 89,
    totalExperience: "7 years",
    sectorSpecialization: [
      { name: "Artificial Intelligence" },
      { name: "Machine Learning" },
    ],
    experienceLevel: ["Mid-level", "Senior", "Lead"],
    linkedinProfile: "https://linkedin.com/in/davidwilson",
    fatherName: "James Wilson",
    motherName: "Susan Wilson",
    medicalProblemDetails: "",
    currentAddress: {
      address: "654 Innovation Hub",
      city: "Hyderabad",
      state: "Telangana",
    },
  },
  {
    id: "3006",
    name: "Lisa Anderson",
    email: "lisa.anderson@smartventures.com",
    phone: {
      countryCode: "+91",
      number: "9876543215",
    },
    profileImage: "/person.png",
    designation: "Talent Sourcing Lead",
    company: "Smart Ventures",
    lastOrganization: {
      name: "Smart Ventures",
      position: "Talent Sourcing Lead",
    },
    industry: "Consulting",
    location: "Pune",
    jobStatus: "draft",
    postedDate: "2024-11-20",
    candidatesCount: 23,
    totalExperience: "3 years",
    sectorSpecialization: [
      { name: "Management Consulting" },
      { name: "Strategy" },
    ],
    experienceLevel: ["Junior", "Mid-level"],
    linkedinProfile: "https://linkedin.com/in/lisaanderson",
    fatherName: "Robert Anderson",
    motherName: "Patricia Anderson",
    medicalProblemDetails: "",
    currentAddress: {
      address: "987 Business District",
      city: "Pune",
      state: "Maharashtra",
    },
  },
  {
    id: "3007",
    name: "James Miller",
    email: "james.miller@nextgensolutions.com",
    phone: {
      countryCode: "+91",
      number: "9876543216",
    },
    profileImage: "/person.png",
    designation: "Senior Recruiter",
    company: "NextGen Solutions",
    lastOrganization: {
      name: "NextGen Solutions",
      position: "Senior Recruiter",
    },
    industry: "Manufacturing",
    location: "Kolkata",
    jobStatus: "on-hold",
    postedDate: "2024-11-10",
    candidatesCount: 41,
    totalExperience: "9 years",
    sectorSpecialization: [{ name: "Manufacturing" }, { name: "Supply Chain" }],
    experienceLevel: ["Mid-level", "Senior", "Lead"],
    linkedinProfile: "https://linkedin.com/in/jamesmiller",
    fatherName: "William Miller",
    motherName: "Helen Miller",
    medicalProblemDetails: "Diabetes",
    currentAddress: {
      address: "147 Industrial Area",
      city: "Kolkata",
      state: "West Bengal",
    },
  },
  {
    id: "3008",
    name: "Rachel Green",
    email: "rachel.green@apexinnovations.com",
    phone: {
      countryCode: "+91",
      number: "9876543217",
    },
    profileImage: "/person.png",
    designation: "Recruitment Consultant",
    company: "Apex Innovations",
    lastOrganization: {
      name: "Apex Innovations",
      position: "Recruitment Consultant",
    },
    industry: "Media",
    location: "Ahmedabad",
    jobStatus: "active",
    postedDate: "2024-12-02",
    candidatesCount: 56,
    totalExperience: "4 years",
    sectorSpecialization: [
      { name: "Media & Entertainment" },
      { name: "Creative Services" },
    ],
    experienceLevel: ["Junior", "Mid-level"],
    linkedinProfile: "https://linkedin.com/in/rachelgreen",
    fatherName: "Leonard Green",
    motherName: "Monica Green",
    medicalProblemDetails: "",
    currentAddress: {
      address: "258 Creative Hub",
      city: "Ahmedabad",
      state: "Gujarat",
    },
  },
  {
    id: "3009",
    name: "Kevin Brown",
    email: "kevin.brown@quantumsystems.com",
    phone: {
      countryCode: "+91",
      number: "9876543218",
    },
    profileImage: "/person.png",
    designation: "Technical Recruiter",
    company: "Quantum Systems",
    lastOrganization: {
      name: "Quantum Systems",
      position: "Technical Recruiter",
    },
    industry: "Technology",
    location: "Jaipur",
    jobStatus: "posted",
    postedDate: "2024-11-25",
    candidatesCount: 34,
    totalExperience: "5 years",
    sectorSpecialization: [
      { name: "Quantum Computing" },
      { name: "Advanced Technologies" },
    ],
    experienceLevel: ["Mid-level", "Senior"],
    linkedinProfile: "https://linkedin.com/in/kevinbrown",
    fatherName: "Thomas Brown",
    motherName: "Sarah Brown",
    medicalProblemDetails: "",
    currentAddress: {
      address: "369 Tech Valley",
      city: "Jaipur",
      state: "Rajasthan",
    },
  },
  {
    id: "3010",
    name: "Amanda Taylor",
    email: "amanda.taylor@synergycorp.com",
    phone: {
      countryCode: "+91",
      number: "9876543219",
    },
    profileImage: "/person.png",
    designation: "Head of Talent Acquisition",
    company: "Synergy Corp",
    lastOrganization: {
      name: "Synergy Corp",
      position: "Head of Talent Acquisition",
    },
    industry: "Real Estate",
    location: "Surat",
    jobStatus: "active",
    postedDate: "2024-12-04",
    candidatesCount: 72,
    totalExperience: "10 years",
    sectorSpecialization: [
      { name: "Real Estate" },
      { name: "Property Development" },
    ],
    experienceLevel: ["Senior", "Lead"],
    linkedinProfile: "https://linkedin.com/in/amandataylor",
    fatherName: "Richard Taylor",
    motherName: "Linda Taylor",
    medicalProblemDetails: "",
    currentAddress: {
      address: "741 Property Square",
      city: "Surat",
      state: "Gujarat",
    },
  },
];
