export const trainersFilters = [
  {
    label: "Skills",
    componentType: "multi-select",
    placeholder: "Select Skills",
    name: "skills",
    options: [
      { id: "corporate-training", label: "Corporate Training" },
      { id: "technical-skills", label: "Technical Skills" },
      { id: "soft-skills", label: "Soft Skills" },
      { id: "leadership-development", label: "Leadership Development" },
      { id: "communication", label: "Communication" },
      { id: "project-management", label: "Project Management" },
      { id: "data-analytics", label: "Data Analytics" },
      { id: "digital-marketing", label: "Digital Marketing" },
      { id: "sales-training", label: "Sales Training" },
      { id: "customer-service", label: "Customer Service" },
    ],
  },
  {
    label: "Industry",
    componentType: "multi-select",
    placeholder: "Select Industry",
    name: "industry",
    options: [
      { id: "technology", label: "Technology" },
      { id: "finance", label: "Finance" },
      { id: "healthcare", label: "Healthcare" },
      { id: "education", label: "Education" },
      { id: "manufacturing", label: "Manufacturing" },
      { id: "sales-marketing", label: "Sales & Marketing" },
      { id: "hr-management", label: "HR & Management" },
      { id: "project-management", label: "Project Management" },
      { id: "soft-skills", label: "Soft Skills" },
      { id: "leadership", label: "Leadership" },
    ],
  },
  {
    label: "Experience",
    componentType: "multi-select",
    placeholder: "Select Experience",
    name: "experience",
    options: [
      { id: "beginner", label: "Beginner (0-2 years)" },
      { id: "intermediate", label: "Intermediate (2-5 years)" },
      { id: "experienced", label: "Experienced (5-10 years)" },
      { id: "expert", label: "Expert (10+ years)" },
    ],
  },
  {
    label: "Location",
    componentType: "multi-select",
    placeholder: "Select Locations",
    name: "location",
    options: [
      { id: "mumbai", label: "Mumbai" },
      { id: "delhi", label: "Delhi" },
      { id: "bangalore", label: "Bangalore" },
      { id: "chennai", label: "Chennai" },
      { id: "hyderabad", label: "Hyderabad" },
      { id: "pune", label: "Pune" },
      { id: "kolkata", label: "Kolkata" },
      { id: "ahmedabad", label: "Ahmedabad" },
      { id: "jaipur", label: "Jaipur" },
      { id: "surat", label: "Surat" },
    ],
  },
];

// Mock data - Replace with actual API call
export const trainers = [
  {
    id: "T001",
    name: "Dr. Rajesh Kumar",
    email: "rajesh.kumar@email.com",
    contact: "+91 9876543210",
    experience: "8 years",
    specialization: "Corporate Training, Leadership Development",
    expertise: "Technology",
    title: "Senior Corporate Trainer",
    location: "Mumbai, India",
    status: "active",
    summary:
      "Experienced corporate trainer specializing in technology leadership and team management. Has conducted 200+ training sessions for Fortune 500 companies.",
    totalTrainings: 180,
    completedTrainings: 165,
    ongoingTrainings: 15,
    rating: 4.8,
    avatar: "/google.png",
    registrationDate: "2024-01-15",
    lastUpdated: "2024-12-08",
    certifications: ["Certified Corporate Trainer", "PMP", "Agile Coach"],
    languages: ["English", "Hindi", "Marathi"],
  },
  {
    id: "T002",
    name: "Priya Sharma",
    email: "priya.sharma@email.com",
    contact: "+91 9876543211",
    experience: "6 years",
    specialization: "Soft Skills, Communication",
    expertise: "HR & Management",
    title: "Communication Specialist",
    location: "Delhi, India",
    status: "active",
    summary:
      "Expert in soft skills development and communication training. Specializes in helping professionals improve their interpersonal and presentation skills.",
    totalTrainings: 150,
    completedTrainings: 142,
    ongoingTrainings: 8,
    rating: 4.9,
    avatar: "/google.png",
    registrationDate: "2024-01-10",
    lastUpdated: "2024-12-07",
    certifications: ["Certified Soft Skills Trainer", "Dale Carnegie Trainer"],
    languages: ["English", "Hindi"],
  },
  {
    id: "T003",
    name: "Amit Patel",
    email: "amit.patel@email.com",
    contact: "+91 9876543212",
    experience: "5 years",
    specialization: "Technical Skills, Data Analytics",
    expertise: "Technology",
    title: "Technical Training Specialist",
    location: "Bangalore, India",
    status: "busy",
    summary:
      "Technical trainer with expertise in data analytics, programming, and emerging technologies. Focuses on upskilling technical teams.",
    totalTrainings: 120,
    completedTrainings: 108,
    ongoingTrainings: 12,
    rating: 4.7,
    avatar: "/google.png",
    registrationDate: "2024-01-05",
    lastUpdated: "2024-12-06",
    certifications: [
      "Google Analytics Certified",
      "AWS Certified",
      "Python Institute Certified",
    ],
    languages: ["English", "Hindi", "Gujarati"],
  },
  {
    id: "T004",
    name: "Sneha Reddy",
    email: "sneha.reddy@email.com",
    contact: "+91 9876543213",
    experience: "7 years",
    specialization: "Sales Training, Customer Service",
    expertise: "Sales & Marketing",
    title: "Sales Training Manager",
    location: "Chennai, India",
    status: "active",
    summary:
      "Sales training expert with proven track record in improving sales performance. Specializes in customer relationship management and sales methodologies.",
    totalTrainings: 200,
    completedTrainings: 185,
    ongoingTrainings: 15,
    rating: 4.6,
    avatar: "/google.png",
    registrationDate: "2024-01-20",
    lastUpdated: "2024-12-09",
    certifications: ["Certified Sales Professional", "CRM Specialist"],
    languages: ["English", "Hindi", "Telugu", "Tamil"],
  },
  {
    id: "T005",
    name: "Vikram Singh",
    email: "vikram.singh@email.com",
    contact: "+91 9876543214",
    experience: "10 years",
    specialization: "Project Management, Leadership",
    expertise: "Project Management",
    title: "Senior Project Management Trainer",
    location: "Hyderabad, India",
    status: "active",
    summary:
      "Seasoned project management trainer with extensive experience in Agile, Scrum, and traditional project management methodologies.",
    totalTrainings: 250,
    completedTrainings: 235,
    ongoingTrainings: 15,
    rating: 4.9,
    avatar: "/google.png",
    registrationDate: "2024-01-12",
    lastUpdated: "2024-12-05",
    certifications: ["PMP", "Scrum Master", "Agile Coach", "PRINCE2"],
    languages: ["English", "Hindi"],
  },
  {
    id: "T006",
    name: "Kavya Nair",
    email: "kavya.nair@email.com",
    contact: "+91 9876543215",
    experience: "4 years",
    specialization: "Digital Marketing, Social Media",
    expertise: "Sales & Marketing",
    title: "Digital Marketing Trainer",
    location: "Pune, India",
    status: "available",
    summary:
      "Digital marketing specialist focusing on modern marketing strategies, social media marketing, and content creation training.",
    totalTrainings: 90,
    completedTrainings: 82,
    ongoingTrainings: 8,
    rating: 4.5,
    avatar: "/google.png",
    registrationDate: "2024-01-25",
    lastUpdated: "2024-12-04",
    certifications: [
      "Google Ads Certified",
      "Facebook Marketing Certified",
      "HubSpot Certified",
    ],
    languages: ["English", "Hindi", "Malayalam"],
  },
];
