export const candidatesFilters = [
  {
    label: "Status",
    componentType: "multi-select",
    placeholder: "Select Status",
    name: "status",
    options: [
      { id: "active", label: "Active" },
      { id: "inactive", label: "Inactive" },
      { id: "hired", label: "Hired" },
      { id: "blacklisted", label: "Blacklisted" },
    ],
  },
  {
    label: "Registration Date",
    componentType: "calendar",
    placeholder: "Select Date",
    name: "registrationDate",
  },
  {
    label: "Industry",
    componentType: "multi-select",
    placeholder: "Select Industries",
    name: "industry",
    options: [
      { id: "technology", label: "Technology" },
      { id: "finance", label: "Finance" },
      { id: "healthcare", label: "Healthcare" },
      { id: "education", label: "Education" },
      { id: "manufacturing", label: "Manufacturing" },
      { id: "retail", label: "Retail" },
      { id: "e-commerce", label: "E-commerce" },
      { id: "consulting", label: "Consulting" },
      { id: "media", label: "Media & Entertainment" },
      { id: "real-estate", label: "Real Estate" },
    ],
  },
  {
    label: "Location",
    componentType: "multi-select",
    placeholder: "Select Locations",
    name: "location",
    options: [
      { id: "mumbai", label: "Mumbai" },
      { id: "delhi", label: "Delhi" },
      { id: "bangalore", label: "Bangalore" },
      { id: "chennai", label: "Chennai" },
      { id: "hyderabad", label: "Hyderabad" },
      { id: "pune", label: "Pune" },
      { id: "kolkata", label: "Kolkata" },
      { id: "ahmedabad", label: "Ahmedabad" },
      { id: "jaipur", label: "Jaipur" },
      { id: "surat", label: "Surat" },
    ],
  },
  {
    label: "Experience Level",
    componentType: "multi-select",
    placeholder: "Select Experience",
    name: "experience",
    options: [
      { id: "fresher", label: "Fresher (0-1 years)" },
      { id: "junior", label: "Junior (1-3 years)" },
      { id: "mid-level", label: "Mid-level (3-5 years)" },
      { id: "senior", label: "Senior (5-8 years)" },
      { id: "lead", label: "Lead (8+ years)" },
    ],
  },
  {
    label: "Skills",
    componentType: "multi-select",
    placeholder: "Select Skills",
    name: "skills",
    options: [
      { id: "javascript", label: "JavaScript" },
      { id: "python", label: "Python" },
      { id: "java", label: "Java" },
      { id: "react", label: "React" },
      { id: "nodejs", label: "Node.js" },
      { id: "sql", label: "SQL" },
      { id: "aws", label: "AWS" },
      { id: "docker", label: "Docker" },
      { id: "mongodb", label: "MongoDB" },
      { id: "kubernetes", label: "Kubernetes" },
    ],
  },
];

// Mock data - Replace with actual API call
export const candidates = [
  {
    id: "2001",
    name: "John Doe",
    email: "john.doe@email.com",
    contact: "+91 9876543210",
    experience: "3 years",
    skills: "React, Node.js, MongoDB",
    industry: "Technology",
    occupation: "Full Stack Developer",
    location: "Mumbai, India",
    status: "active",
    summary:
      "Experienced full-stack developer with expertise in modern web technologies. Passionate about creating scalable and efficient web applications.",
    totalApplications: 15,
    selectedApplications: 3,
    rejectedApplications: 8,
    pendingApplications: 4,
    avatar: "/google.png",
    registrationDate: "2024-01-15",
    lastUpdated: "2024-12-08",
  },
  {
    id: "2002",
    name: "Jane Smith",
    email: "jane.smith@email.com",
    contact: "+91 9876543211",
    experience: "5 years",
    skills: "Python, Django, PostgreSQL",
    industry: "Technology",
    occupation: "Backend Developer",
    location: "Delhi, India",
    status: "active",
    summary:
      "Senior backend developer with strong expertise in Python ecosystem. Has worked on large-scale distributed systems and API development.",
    totalApplications: 20,
    selectedApplications: 5,
    rejectedApplications: 10,
    pendingApplications: 5,
    avatar: "/google.png",
    registrationDate: "2024-01-10",
    lastUpdated: "2024-12-07",
  },
  {
    id: "2003",
    name: "Mike Johnson",
    email: "mike.johnson@email.com",
    contact: "+91 9876543212",
    experience: "2 years",
    skills: "Java, Spring Boot, MySQL",
    industry: "Finance",
    occupation: "Java Developer",
    location: "Bangalore, India",
    status: "hired",
    summary:
      "Java developer with strong problem-solving skills. Experience in building enterprise applications using Spring framework.",
    totalApplications: 12,
    selectedApplications: 2,
    rejectedApplications: 6,
    pendingApplications: 4,
    avatar: "/google.png",
    registrationDate: "2024-01-05",
    lastUpdated: "2024-12-06",
  },
  {
    id: "2004",
    name: "Sarah Wilson",
    email: "sarah.wilson@email.com",
    contact: "+91 9876543213",
    experience: "4 years",
    skills: "Angular, TypeScript, AWS",
    industry: "Healthcare",
    occupation: "Frontend Developer",
    location: "Chennai, India",
    status: "active",
    summary:
      "Frontend developer specializing in Angular and modern TypeScript. Experience with cloud deployment on AWS platform.",
    totalApplications: 18,
    selectedApplications: 4,
    rejectedApplications: 9,
    pendingApplications: 5,
    avatar: "/google.png",
    registrationDate: "2024-01-20",
    lastUpdated: "2024-12-09",
  },
  {
    id: "2005",
    name: "David Brown",
    email: "david.brown@email.com",
    contact: "+91 9876543214",
    experience: "6 years",
    skills: "DevOps, Docker, Kubernetes",
    industry: "Technology",
    occupation: "DevOps Engineer",
    location: "Hyderabad, India",
    status: "active",
    summary:
      "DevOps engineer with expertise in containerization and orchestration. Experienced in CI/CD pipeline setup and cloud infrastructure management.",
    totalApplications: 22,
    selectedApplications: 6,
    rejectedApplications: 12,
    pendingApplications: 4,
    avatar: "/google.png",
    registrationDate: "2024-01-12",
    lastUpdated: "2024-12-05",
  },
  {
    id: "2006",
    name: "Lisa Garcia",
    email: "lisa.garcia@email.com",
    contact: "+91 9876543215",
    experience: "1 year",
    skills: "HTML, CSS, JavaScript",
    industry: "E-commerce",
    occupation: "Junior Frontend Developer",
    location: "Pune, India",
    status: "active",
    summary:
      "Junior frontend developer with a strong foundation in web development fundamentals. Eager to learn and grow in the field of web development.",
    totalApplications: 8,
    selectedApplications: 1,
    rejectedApplications: 4,
    pendingApplications: 3,
    avatar: "/google.png",
    registrationDate: "2024-01-25",
    lastUpdated: "2024-12-04",
  },
];
