export const jobsAndTrainingsTabs = [
  {
    id: "jobs",
    name: "Jobs",
    icon: null,
  },
  {
    id: "trainings",
    name: "Trainings",
    icon: null,
  },
];

export const jobsAndTrainingsFilters = [
  {
    label: "Status",
    componentType: "multi-select",
    placeholder: "Select Status",
    name: "status",
    options: [
      { id: "active", label: "Active" },
      { id: "ended", label: "Ended" },
      { id: "pending", label: "Pending" },
    ],
  },
  {
    label: "Job Type",
    componentType: "multi-select",
    placeholder: "Select Job Type",
    name: "jobType",
    options: [
      { id: "full-time", label: "Full Time" },
      { id: "part-time", label: "Part Time" },
      { id: "contract", label: "Contract" },
      { id: "internship", label: "Internship" },
      { id: "freelance", label: "Freelance" },
    ],
  },
  {
    label: "Experience Level",
    componentType: "multi-select",
    placeholder: "Select Experience Level",
    name: "experienceLevel",
    options: [
      { id: "entry", label: "Entry Level (0-1 years)" },
      { id: "junior", label: "Junior (1-3 years)" },
      { id: "mid", label: "Mid Level (3-5 years)" },
      { id: "senior", label: "Senior (5-8 years)" },
      { id: "lead", label: "Lead (8+ years)" },
    ],
  },
  {
    label: "City",
    componentType: "multi-select",
    placeholder: "Select Cities",
    name: "city",
    options: [
      { id: "mumbai", label: "Mumbai" },
      { id: "delhi", label: "Delhi" },
      { id: "bangalore", label: "Bangalore" },
      { id: "chennai", label: "Chennai" },
      { id: "hyderabad", label: "Hyderabad" },
      { id: "pune", label: "Pune" },
      { id: "kolkata", label: "Kolkata" },
      { id: "ahmedabad", label: "Ahmedabad" },
      { id: "jaipur", label: "Jaipur" },
      { id: "surat", label: "Surat" },
    ],
  },
  {
    label: "State",
    componentType: "multi-select",
    placeholder: "Select States",
    name: "state",
    options: [
      { id: "maharashtra", label: "Maharashtra" },
      { id: "delhi", label: "Delhi" },
      { id: "karnataka", label: "Karnataka" },
      { id: "tamil-nadu", label: "Tamil Nadu" },
      { id: "telangana", label: "Telangana" },
      { id: "west-bengal", label: "West Bengal" },
      { id: "gujarat", label: "Gujarat" },
      { id: "rajasthan", label: "Rajasthan" },
      { id: "uttar-pradesh", label: "Uttar Pradesh" },
      { id: "kerala", label: "Kerala" },
    ],
  },
  {
    label: "Mode of Work",
    componentType: "multi-select",
    placeholder: "Select Mode of Work",
    name: "modeOfWork",
    options: [
      { id: "remote", label: "Remote" },
      { id: "onsite", label: "Onsite" },
      { id: "hybrid", label: "Hybrid" },
    ],
  },
  {
    label: "Gender Preference",
    componentType: "multi-select",
    placeholder: "Select Gender Preference",
    name: "genderPreference",
    options: [
      { id: "male", label: "Male" },
      { id: "female", label: "Female" },
      { id: "any", label: "Any" },
    ],
  },
  {
    label: "Walk-in Interview",
    componentType: "multi-select",
    placeholder: "Select Walk-in Interview",
    name: "isWalkInInterview",
    options: [
      { id: "true", label: "Yes" },
      { id: "false", label: "No" },
    ],
  },
];

// Mock data for jobs
export const jobsData = [
  {
    id: "J001",
    name: "Senior React Developer",
    appliedTime: "2024-01-15T10:30:00Z",
    company: "TechCorp Solutions",
    candidates: 45,
    location: "Mumbai",
    experience: "3-5 years",
    status: "active",
    industry: "technology",
    description:
      "We are looking for an experienced React developer to join our dynamic team...",
    postedDate: "2024-01-10T09:00:00Z",
  },
  {
    id: "J002",
    name: "Data Scientist",
    appliedTime: "2024-01-18T14:20:00Z",
    company: "Healthcare Plus",
    candidates: 32,
    location: "Delhi",
    experience: "2-4 years",
    status: "active",
    industry: "healthcare",
    description:
      "Join our data science team to work on cutting-edge healthcare analytics...",
    postedDate: "2024-01-12T11:00:00Z",
  },
  {
    id: "J003",
    name: "Product Manager",
    appliedTime: "2024-01-20T09:15:00Z",
    company: "EduTech Innovations",
    candidates: 28,
    location: "Bangalore",
    experience: "4-6 years",
    status: "ended",
    industry: "education",
    description:
      "Lead product development for our innovative education platform...",
    postedDate: "2024-01-08T08:30:00Z",
  },
  {
    id: "J004",
    name: "Full Stack Developer",
    appliedTime: "2024-01-22T16:45:00Z",
    company: "FinTech Services",
    candidates: 67,
    location: "Chennai",
    experience: "2-5 years",
    status: "active",
    industry: "finance",
    description:
      "Build robust financial applications using modern web technologies...",
    postedDate: "2024-01-15T10:15:00Z",
  },
  {
    id: "J005",
    name: "UI/UX Designer",
    appliedTime: "2024-01-25T11:30:00Z",
    company: "Retail Giants",
    candidates: 23,
    location: "Hyderabad",
    experience: "1-3 years",
    status: "pending",
    industry: "retail",
    description:
      "Create stunning user experiences for our e-commerce platform...",
    postedDate: "2024-01-20T14:00:00Z",
  },
  {
    id: "J006",
    name: "DevOps Engineer",
    appliedTime: "2024-01-28T13:20:00Z",
    company: "Manufacturing Pro",
    candidates: 19,
    location: "Pune",
    experience: "3-6 years",
    status: "pending",
    industry: "manufacturing",
    description:
      "Streamline our deployment processes and infrastructure management...",
    postedDate: "2024-01-22T09:30:00Z",
  },
  {
    id: "J007",
    name: "Business Analyst",
    appliedTime: "2024-01-30T15:10:00Z",
    company: "Consulting Experts",
    candidates: 41,
    location: "Kolkata",
    experience: "2-4 years",
    status: "ended",
    industry: "consulting",
    description:
      "Analyze business requirements and provide strategic recommendations...",
    postedDate: "2024-01-18T12:45:00Z",
  },
  {
    id: "J008",
    name: "Mobile App Developer",
    appliedTime: "2024-02-02T10:00:00Z",
    company: "StartUp Hub",
    candidates: 35,
    location: "Ahmedabad",
    experience: "1-4 years",
    status: "active",
    industry: "technology",
    description:
      "Develop innovative mobile applications for iOS and Android platforms...",
    postedDate: "2024-01-25T08:00:00Z",
  },
];

// Mock data for trainings
export const trainingsData = [
  {
    id: "T001",
    name: "Advanced React Training",
    appliedTime: "2024-01-16T11:00:00Z",
    company: "TechCorp Solutions",
    candidates: 25,
    location: "Mumbai",
    experience: "1-3 years",
    status: "active",
    industry: "technology",
    description:
      "Comprehensive React training covering hooks, context, and advanced patterns...",
    postedDate: "2024-01-11T10:00:00Z",
  },
  {
    id: "T002",
    name: "Data Analytics Bootcamp",
    appliedTime: "2024-01-19T14:30:00Z",
    company: "Healthcare Plus",
    candidates: 18,
    location: "Delhi",
    experience: "0-2 years",
    status: "active",
    industry: "healthcare",
    description:
      "Learn data analytics tools and techniques for healthcare applications...",
    postedDate: "2024-01-13T09:15:00Z",
  },
  {
    id: "T003",
    name: "Product Management Essentials",
    appliedTime: "2024-01-21T09:45:00Z",
    company: "EduTech Innovations",
    candidates: 22,
    location: "Bangalore",
    experience: "2-4 years",
    status: "ended",
    industry: "education",
    description:
      "Master the fundamentals of product management in the education sector...",
    postedDate: "2024-01-09T11:30:00Z",
  },
  {
    id: "T004",
    name: "FinTech Development Program",
    appliedTime: "2024-01-23T16:20:00Z",
    company: "FinTech Services",
    candidates: 31,
    location: "Chennai",
    experience: "1-4 years",
    status: "active",
    industry: "finance",
    description:
      "Specialized training in financial technology development and security...",
    postedDate: "2024-01-16T13:00:00Z",
  },
  {
    id: "T005",
    name: "Digital Marketing Masterclass",
    appliedTime: "2024-01-26T12:15:00Z",
    company: "Retail Giants",
    candidates: 29,
    location: "Hyderabad",
    experience: "0-3 years",
    status: "pending",
    industry: "retail",
    description: "Complete guide to digital marketing for retail businesses...",
    postedDate: "2024-01-21T15:45:00Z",
  },
  {
    id: "T006",
    name: "Cloud Infrastructure Training",
    appliedTime: "2024-01-29T14:00:00Z",
    company: "Manufacturing Pro",
    candidates: 16,
    location: "Pune",
    experience: "2-5 years",
    status: "pending",
    industry: "manufacturing",
    description:
      "Learn cloud infrastructure management for manufacturing systems...",
    postedDate: "2024-01-23T10:20:00Z",
  },
  {
    id: "T007",
    name: "Strategic Consulting Workshop",
    appliedTime: "2024-01-31T16:30:00Z",
    company: "Consulting Experts",
    candidates: 20,
    location: "Kolkata",
    experience: "3-6 years",
    status: "ended",
    industry: "consulting",
    description: "Advanced workshop on strategic consulting methodologies...",
    postedDate: "2024-01-19T14:10:00Z",
  },
  {
    id: "T008",
    name: "Startup Accelerator Program",
    appliedTime: "2024-02-03T11:45:00Z",
    company: "StartUp Hub",
    candidates: 33,
    location: "Ahmedabad",
    experience: "0-2 years",
    status: "active",
    industry: "technology",
    description:
      "Intensive program for early-stage startup founders and entrepreneurs...",
    postedDate: "2024-01-26T09:00:00Z",
  },
];
